management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true


jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP


url:
  service:
    file: http://localhost:8010
    meta: http://localhost:8011
    notification: http://localhost:8012
    auth: http://localhost:9000